# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "./build"
  command = "npm run build && mv ._headers build/_headers"

[context.master]
  publish = "./build"
  command = "npm run build"


